### ISSUE TITLE
Rhapsodies of Vana'diel Data

### ISSUE THREAD

**Issue by funkworkz** [Windower/POLUtils#15]
Please add shortcuts in the menu for Rhapsodies of Vana'diel.

Missions:
English .DAT is ROM/333/4.DAT
Japanese .DAT is ROM/333/3.DAT

Maps:
Escha - Zi'Tah is  ROM/333/8.DAT
Escha - Ru'Aun is ROM/337/37.DAT

Dialogue:
Escha - Zi'Tah is  ROM/332/106.DAT
Escha - Ru'Aun is ROM/337/63.DAT

NPC/Monster List
I do not know where either of these are.

**Comment by hinbe** [comment]
NPC/Monster List
Escha - Zi'Tah is ROM/332/109.DAT
Escha - Ru'Aun is ROM/337/66.DAT

**Comment by hinbe** [comment]
Dialogue :
Japanese
Escha - Zi'Tah is ROM/332/105.DAT
Escha - Ru'Aun is ROM/337/62.DAT

**Comment by hinbe** [comment]
Unity chat:
English .DAT is ROM/337/68.DAT
Japanese .DAT is ROM/337/67.DAT

**Comment by TeoTwawki** [comment]
I'll have a pull request for these soonish

**Comment by TeoTwawki** [comment]
Got most of it done: #17
I have a bunch of other non FFXI related work that is going to keep me away from the rest of it for awhile. Someone else will have to get Unity Chat or else wait awhile longer.

**Comment by alphaONE2** [comment]
Going to close this. I've opened issue #18 as a separate issue for unity chat.
