### ISSUE TITLE
Item Level wrong

### ISSUE THREAD

**Issue by funkworkz** [Windower/POLUtils#16]
Some pieces of armor and weapons are showing item level 375. A couple weapons are showing 256.

**Comment by alphaONE2** [comment]
Which means it's apparently a single byte, and there's an unknown field after ilvl.
@z16: ResourcesExtractor probably has the same bug.

**Comment by TeoTwawki** [comment]
I think it might be not even the full byte, possibly 7 bits is item level and the rest of the bits go to something else.

But at a minimum this is def 1 byte and no larger.

**Comment by TeoTwawki** [comment]
I think I or Wren will have a PR for this shortly
