### ISSUE TITLE
Unable to read NPC info from DATs after v1.1.6037.10692

### ISSUE THREAD

**Issue by mcmsweet** [Windower/POLUtils#32]
Somewhere along the way a change broke the ability to read NPC info from DAT files. The last release of this project that I can read NPC DAT info in is v1.1.6037.10692. In the latest version only images are made available for viewing.

**Comment by Evilocity** [comment]
Been running 1.1.5x forever, but thought I may as well install the current version 1.1.6238

Had a problem similar to the above where on attempting to read item data, it gets stuck on "Parsing Spell & Ability Info".  Installed two releases earlier (1.1.6037) and it works fine.

Seems the 1.1.6156 release that "Fixed "Spell & Ability Info" parsing, refactoring" instead broke that exact thing? This is from a program both generated by the .msi and compiled from the project directly.  Running Win10 64-bit.

Can this be patched up?  It'd be nice to have the flags that BG-Wiki worked out displayed correctly as per the most recent release.

**Comment by z16** [comment]
Should be fixed, let me know if you still experience the issue.

**Comment by Evilocity** [comment]
Worked a charm, ta!
