### ISSUE TITLE
Getting this to run without installing .NET 2.0

### ISSUE THREAD

**Issue by zombie343** [Windower/POLUtils#36]
I had to just make the following change to get POLUtils to run in .NET4.0 (instead of installing .NET 2.0, yuck):

1. Create a file, called POLUtils.exe.config
2. Put this in the file:
```
<configuration>
  <startup>
    <supportedRuntime version="v4.0"/>
  </startup>
</configuration>
```
This is just a band-aid until someone actually goes ahead and ports this to a later version of .NET because I can't imagine this will be backwards compatible forever. I've only tested exporting item's icons, but I imagine not all functionality works in .NET 4.0 without porting the code over. If this doesn't work for you, install .NET 2.0, I guess.

**Comment by z16** [comment]
Updated it to .NET 4.8, please open another issue if you find anything that broke.

**Comment by zombie343** [comment]
Will do. Thank you.
