### ISSUE TITLE
French / German weapon data empty

### ISSUE THREAD

**Issue by scragg0x** [Windower/POLUtils#8]
When using the mass extractor

**Comment by IryokuChevalier** [comment]
SE officially removed the option to play in French and German on 2014-07-08 ([announcement](http://www.playonline.com/pcd/topics/ff11eu/1404/topics_all.html)); they have not added any new French or German translations since then.

**Comment by scragg0x** [comment]
Wow.  I guess I will have to fallback to english for those.
